### PR TITLE
Unify `rr-opts` and `gdb-opts` behavior. 

### PR DESCRIPTION
**Pull request by DrRuhe**
This is a continuation to #12.

I think the arguments should have the same syntax for specifying them.

Now, both can be specified with their specific flag:

`cargo rr replay --rr-opts="-s 1234" --gdb-opts="-a"`
Note that equal signs are required to eliminate ambiguity. Otherwise clap would parse `--rr-opts "-s 1234"` as specifying the -s flag. 

In the [unified-across-commands](https://github.com/DrRuhe/cargo-rr/compare/hyphens...DrRuhe:cargo-rr:unified-across-commands) branch I have also adjusted the behavior to be consistent, you can decide if that makes sense, given that the other commands do not support `gdb-opts` and only `rr-opts`

### CODE REVIEW

**Comment by dzfranklin** [comment]
I like unifying across commands. Can you push that to this PR?

**Comment by DrRuhe** [comment]
Oh, thanks for the quick reply :) 

Now its unified.

**Review by dzfranklin — APPROVED** [review]
lgtm

**Comment by dzfranklin** [comment]
fyi @DrRuhe and @NickHu I just published a release with this change

**Pull request merged**
